# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
    files: \.py$
  - id: debug-statements
    files: \.py$
  - id: trailing-whitespace
    files: \.py$

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.0
  hooks:
  - id: ruff-format
    files: \.py$
  - id: ruff
    args: ["--fix"]
    files: \.py$